# tasks file for validators
- name: Create base path for validator {{id}} 
  file: 
    path: "{{ base_path }}/{{id}}"
    state: directory 
    mode: 0755

- name: fetch key node for validator {{id}} 
  uri:
    url: "http://{{vault.ip}}:8200/v1/secret/data/da/testnet/{{id}}"
    headers:
      X-Vault-Token: "{{vault.token}}"
  register: secret

- name: create entrypoint for validator {{id}}
  template:
    src: "./templates/da.sh"
    dest: "{{ base_path }}/{{id}}/da.sh"
    mode: 755

- name: setup container for validator {{id}} 
  community.docker.docker_container:
    name: "{{id}}"
    image: 0xpolygon/avail:ava-154
    entrypoint: "/da/bin/da.sh"
    ports:
      - "{{ port }}:{{ port }}" 
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"openmetrics_endpoint":"http://%%host%%:9615/metrics", "namespace": "avail", "metrics": ["substrate*"]}]'
    volumes:
      - "{{base_path}}/{{id}}/da.sh:/da/bin/da.sh"
      - "{{base_path}}/{{id}}/state:/da/state"
      - "{{base_path}}/{{id}}/keystore:/da/keystore"

- name: Add BABE private key to validator {{id}}
  import_tasks: "load_key.yml"
  vars:
    container: "{{id}}"
    sk: "{{secret.json.data.data.sk}}"
    key_type: "babe"
    scheme: "Sr25519"

- name: Add GRANDPA private key to validator {{id}}
  import_tasks: "load_key.yml"
  vars:
    container: "{{id}}"
    sk: "{{secret.json.data.data.sk}}"
    key_type: "gran"
    scheme: "Ed25519"

- name: Add Im-online private key to validator {{id}}
  import_tasks: "load_key.yml"
  vars:
    container: "{{id}}"
    sk: "{{secret.json.data.data.sk}}"
    key_type: "imon"
    scheme: "Sr25519"

- name: Add Authority Discovery private key to validator {{id}}
  import_tasks: "load_key.yml"
  vars:
    container: "{{id}}"
    sk: "{{secret.json.data.data.sk}}"
    key_type: "audi"
    scheme: "Sr25519"

- name: Add Auth private key to validator {{id}}
  import_tasks: "load_key.yml"
  vars:
    container: "{{id}}"
    sk: "{{secret.json.data.data.sk}}"
    key_type: "auth"
    scheme: "Sr25519"
