- hosts: "{{host}}"
  become: true
  tasks:
    - name: "rotate keys on {{container}}"
      community.docker.docker_container_exec:
        container: "{{container}}"
        debug: true
        argv: 
          - curl
          - -s
          - -H
          - Content-Type:application/json
          - -d 
          - '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}'
          - "http://localhost:9933"
      register: keys

    - name: Print rotate keys output
      debug:
        var: keys.stdout_lines
