- name: Create deployment_name file
  ansible.builtin.template:
    force: yes
    src: "./templates/avail-deployment"
    dest: "/etc/avail-deployment"
    mode: '0755'
    owner: ubuntu
    group: ubuntu

# - name: create motd logo
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/motd.sh"
#     dest: "/etc/update-motd.d/00-avl-logo"
#     mode: '0755'
#     owner: ubuntu
#     group: ubuntu
#
# - name: create sysinfo
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/info.sh"
#     dest: "/etc/update-motd.d/10-sys-info"
#     mode: '0755'
#     owner: ubuntu
#     group: ubuntu
#
# - name: create network info
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/network.sh"
#     dest: "/etc/update-motd.d/20-network-info"
#     mode: '0755'
#     owner: ubuntu
#     group: ubuntu
