version: "3.3"
services:
  fullnode:
    build:  
        context: ./images/da
        dockerfile: Dockerfile-dev
        args:
          - BRANCH=develop
          - FEATURES=kate/maximum-block-size
    # ports:
    #   - 9944:9944
    #   - 9933:9933
    entrypoint: /da/bin/data-avail
    command:
      --dev
      --tmp
      --unsafe-rpc-external 
      --unsafe-ws-external
    network_mode: host
  bootstraplc:
    build:  
        context: ./images/client
        dockerfile: Dockerfile-dev
        args:
          - BRANCH=luka/randomize-seed
    depends_on:
      - fullnode
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "127.0.0.1:9944",
      "--",
      "/app/avail-light/start.sh"
    ]
    # ports:
    #   - 9000:7000
    #   - 37000:37000
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - FULL_NODE_RPC=["http://127.0.0.1:9933"]
      - FULL_NODE_WS=["ws://127.0.0.1:9944"]
      - LOG_LEVEL="INFO"
      - PARALLEL_TASKS=8
      - IPFS_SEED=1
      - IPFS_PORT="37000"
      - HTTP_SERVER_PORT="7000"
      - DISABLE_RPC=true
      # - BLOCK_PROCESSING_DELAY=10
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: host
    # networks:
    #  - host_net
  lc:
    build:  
        context: ./images/client
        dockerfile: Dockerfile-dev
        args:
          - BRANCH=luka/randomize-seed
    depends_on:
      - bootstraplc
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "127.0.0.1:37000",
      "--",
      "/app/avail-light/start.sh"
    ]
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - FULL_NODE_RPC=["http://127.0.0.1:9933"]
      - FULL_NODE_WS=["ws://127.0.0.1:9944"]
      - LOG_LEVEL="INFO"
      - PARALLEL_TASKS=8
      - IPFS_SEED_RANDOM=true
      - BOOTSTRAPS=[["12D3KooWMm1c4pzeLPGkkCJMAgFbsfQ8xmVDusg272icWsaNHWzN", "/ip4/127.0.0.1/tcp/37000"]]
      - BLOCK_PROCESSING_DELAY=5
      - IPFS_PORT="38001-38100"
      - HTTP_SERVER_PORT="8000-9000"
      - DISABLE_RPC=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    # networks:
    #  - host_net
  lc_filler:
    build:  
        context: ./images/client
        dockerfile: Dockerfile-dev
        args:
          - BRANCH=luka/randomize-seed
    depends_on:
      - bootstraplc
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "127.0.0.1:37000",
      "--",
      "/app/avail-light/start.sh"
    ]
    # ports:
    #   - 37001-37100
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - FULL_NODE_RPC=["http://127.0.0.1:9933"]
      - FULL_NODE_WS=["ws://127.0.0.1:9944"]
      - LOG_LEVEL="INFO"
      - PARALLEL_TASKS=8
      - IPFS_SEED_RANDOM=true
      - BOOTSTRAPS=[["12D3KooWMm1c4pzeLPGkkCJMAgFbsfQ8xmVDusg272icWsaNHWzN", "/ip4/127.0.0.1/tcp/37000"]]
      - IPFS_PORT="37001-37100"
      - HTTP_SERVER_PORT="9001-10000"
      - BLOCK_MATRIX_PARTITION="1/1"
      - DISABLE_PROOF_VERIFICATION=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #  - host_net
    network_mode: host
networks:
  bootstrap_network:
    name: bootstrap_network
  lc_network_1:
    name: lc_network_1
  lc_network_2:
    name: lc_network_2