version: "3.3"
services:
  alice:
    container_name: alice 
    build:
      context: ./images/da
      args:
        - BRANCH=miguel/mat-3347-new-chain-spec-for-dev-testnet
    image: da:mat-3347
    tmpfs: /tmp
    volumes:
      - alice-state:/da/state
      - ./volume/dev/local.chain_spec.json:/da/chain_spec.json:ro
    ports:
      - 9944:9944
    command: 
      --validator
      --alice
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_VALIDATOR_1
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      --execution Native
      --in-peers 2
      --out-peers 2
      --port 30333 
      --no-prometheus
      --rpc-cors all
      --unsafe-rpc-external
      --unsafe-ws-external
      --ws-port 9944
  bob:
    container_name: bob 
    image: da:mat-3347
    tmpfs: /tmp
    volumes:
      - bob-state:/da/state
      - ./volume/dev/local.chain_spec.json:/da/chain_spec.json:ro
    depends_on:
      - alice
    command:
      --validator
      --bob
      --chain /da/chain_spec.json 
      --base-path /da/state
      --name MATIC_VALIDATOR_2
      --node-key 0000000000000000000000000000000000000000000000000000000000000002
      --execution Native
      --in-peers 2
      --out-peers 2
      --port 30333 
      --bootnodes /dns4/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --no-prometheus
      --rpc-cors all

volumes:
  alice-state:
  bob-state:

# vim: ts=2:et
