- name: Create deployment_name file
  ansible.builtin.template:
    force: yes
    src: "./templates/avail-deployment"
    dest: "/etc/avail-deployment"
    mode: '0755'
    owner: ubuntu
    group: ubuntu
#
# - name: Check whether /etc/avail-deployment contains "{{ deployment_name }}"
#   command: grep -Fxq "{{ deployment_name }}" /etc/avail-deployment
#   register: checkdeployment
#   check_mode: no
#   ignore_errors: yes
#   changed_when: no
#   become: true
#
# - ansible.builtin.assert:
#     that:
#       - checkdeployment.rc == 0
#   become: true
#
# - name: Set a hostname
#   become: true
#   ansible.builtin.hostname:
#     name: "{{ node_hostname }}"
#
# - name: Install aptitude
#   become: true
#   apt:
#     name: aptitude
#     state: latest
#     update_cache: true
#
# - name: Install required system packages
#   become: true
#   tags:
#     - packages
#   apt:
#     pkg:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - software-properties-common
#       - python3-pip
#       - virtualenv
#       - python3-setuptools
#       - zile
#       - net-tools
#       - inxi
#     state: latest
#     update_cache: true
#
# - name: Add Docker GPG apt Key
#   become: true
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#
# - name: Add Docker Repository
#   become: true
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu focal stable
#     state: present
#
# - name: Update apt and install docker-ce
#   become: true
#   apt:
#     name: docker-ce
#     state: latest
#     update_cache: true
#
# - name: Delete motd
#   become: true
#   tags:
#     - motd
#   file:
#     state: absent
#     path: /etc/update-motd.d/
#
# - name: Create MOTD
#   become: true
#   tags:
#     - motd
#   file:
#     state: directory
#     path: /etc/update-motd.d/
#
# - name: create motd logo
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/motd.sh"
#     dest: "/etc/update-motd.d/00-avl-logo"
#     mode: '0755'
#     owner: ubuntu
#     owner: ubuntu
#
# - name: create sysinfo
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/info.sh"
#     dest: "/etc/update-motd.d/10-sys-info"
#     mode: '0755'
#     owner: ubuntu
#     owner: ubuntu
#
# - name: create network info
#   tags:
#     - motd
#   ansible.builtin.template:
#     src: "./templates/network.sh"
#     dest: "/etc/update-motd.d/20-network-info"
#     mode: '0755'
#     owner: ubuntu
#     owner: ubuntu
