log_level = "info"
http_server_host = "127.0.0.1"
# http_server_port = "7001"

# secret_key = { seed = "2" }
# libp2p_port = "37001"
libp2p_psk_path = "avail_ipfs_store"
libp2p_tcp_port_reuse = false


# full_node_rpc = ["http://192.168.40.100:9933"]
# full_node_ws = ["ws://192.168.40.100:9944"]
app_id = 0
confidence = 92.0
avail_path = "avail_path"
# prometheus_port = 9520
disable_client_sync = true
# block_matrix_partition = "1/10"
disable_proof_verification = true
query_proof_rpc_parallel_tasks = 300
max_cells_per_rpc = 1024
dht_parallelization_limit = 20
block_processing_delay = 0

connection_idle_timeout = 30

# bootstraps = [["12D3KooWStAKPADXqJ7cngPYXd2mSANpdgh1xQ34aouufHA2xShz", "/ip4/192.168.40.120/tcp/39000"]]
