FROM rust:1.70.0 AS chef 
# We only pay the installation cost once, 
# it will be cached from the second build onwards
RUN cargo install cargo-chef --version 0.1.31
WORKDIR app

FROM chef AS planner

ARG BRANCH=doesnt_exist
RUN git clone --depth 1 -b ${BRANCH} https://github.com/availproject/avail.git
WORKDIR /app/avail
RUN cargo chef prepare --recipe-path /app/avail/recipe.json

FROM chef AS builder
COPY --from=planner /app/avail/recipe.json recipe.json
RUN apt-get update && \
	apt-get install -y libssl1.1 gettext-base wait-for-it ca-certificates clang protobuf-compiler jq && \
	rm -rf /var/lib/apt/lists 
RUN rustup install nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly

ARG BRANCH=doesnt_exist
ARG RUNTIME_BRANCH=doesnt_exist
ARG FEATURES=""

# Build application
RUN rm -rf avail && git clone --depth 1 -b ${BRANCH} https://github.com/availproject/avail.git
RUN cat /app/recipe.json | jq
# Build dependencies - this is the caching Docker layer!
#RUN cd avail && cargo chef cook --release -p data-avail --features "${FEATURES}" --recipe-path /app/recipe.json


# This will utilize caching and check if rebuild is needed - if the branch has changed, so will this response
ADD https://api.github.com/repos/availproject/avail/commits/${BRANCH} last_commit.json
RUN cd avail && git fetch origin && git reset --hard ${BRANCH}
RUN cd avail && cargo build --release -p data-avail --features "${FEATURES}" && cp /app/avail/target/release/data-avail /app
# Now build runtime
RUN cd avail && git fetch origin && git reset --hard ${RUNTIME_BRANCH}
RUN cd avail && cargo build --release -p da-runtime --features "${FEATURES}" && cp /app/avail/target/release/wbuild/da-runtime/da_runtime.compact.compressed.wasm /app/runtime.wasm

# We do not need the Rust toolchain to run the binary!
FROM debian:bullseye-slim AS runtime

RUN apt-get update && \
	apt-get install -y libssl1.1 gettext-base wait-for-it ca-certificates xxd && \
	rm -rf /var/lib/apt/lists && \
	mkdir -p /da/bin

COPY --from=builder /app/data-avail /da/bin/
COPY --from=builder /app/runtime.wasm /da/bin/
COPY ./resources/* /da/bin/
RUN xxd -p /da/bin/runtime.wasm | tr -d '\n' > wasm.hex

# RUN sed -i 's/WASM_BINARY/\nWASM_BINARY\n/g' /da/bin/chainspec_template.json
# RUN csplit /da/bin/chainspec_template.json '/WASM_BINARY/' '{*}' && sed -i '/WASM_BINARY/d' xx*
# RUN truncate -s -1 xx00
# RUN cat xx00 wasm.hex xx01 > /da/bin/chainspec.json

RUN chmod +x /da/bin/substitute_keyword.sh && /da/bin/substitute_keyword.sh WASM_BINARY /da/bin/chainspec_template.json wasm.hex /da/bin/chainspec.json

WORKDIR /da
VOLUME ["/tmp", "/da/state", "/da/keystore"]
ENTRYPOINT ["/da/bin/data-avail", "--chain", "/da/bin/chainspec.json"]
