---
lineage: 63f6606d-329f-273a-64a1-8bfc06a1b56c
lb_dns: avail-lb-de4268be15138de8.elb.us-west-2.amazonaws.com
node_name: "{{ hostvars[inventory_hostname].tags.Name }}"
avail_domain: "avail.john.dev"
node_hostname: "{{ node_name }}.{{ avail_domain}}"

# depending on how we load blance this might need to be moved to the host level
node_port: 30333
node_ws_port: 9944
node_rpc_port: 9933
node_base_path: /var/avail/
node_docker_tag: 1.0.1
node_network_mode: default
node_in_peers: 50
node_out_peers: 50
node_ws_max_connections: 1000

prometheus:
  port: 9615
  endpoint: "metrics"
