- hosts: all
  become: true
  gather_facts: True
  tags:
    - init
  roles:
    - common
    # - datadog
#
# - hosts: validator:full_node
#   gather_facts: True
#   become: true
#   tags:
#     - availnode
#   roles:
#     - availnode
#
# - hosts: explorer
#   gather_facts: True
#   become: true
#   tags:
#     - explorer
#   roles:
#     - explorer
#
# - hosts: light_client
#   gather_facts: True
#   become: true
#   tags:
#     - light_client
#   roles:
#     - lightclient
