---
# isntall controller dependencies, create new instances and teardown at end
- name: install python and aws dependencies on ansible controller machine
  hosts: localhost
  collections:
  - amazon.aws
  roles:
     - role: staticdev.pyenv
       pyenv_path: "/tmp/pyenv"
       pyenv_owner: "root"
       pyenv_global:
         - 3.6.4
       pyenv_enable_autocompletion: false
       pyenv_python_versions:
         - 3.6.4
  environment:
    MAX_EVENT_RES_DATA: 90000000
  tasks:
  - name: setup controller environment
    shell:
      cmd: |
        export PATH="/tmp/pyenv/shims:$PATH"
        eval "$(. /tmp/pyenv/.pyenvrc && pyenv init --path)"
        . /tmp/pyenv/.pyenvrc && pyenv versions
        . /tmp/pyenv/.pyenvrc && pyenv global 3.6.4
        unset PYTHONPATH
        pip install --user boto3 botocore
        mkdir -p /opt/avail_repo
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        sudo yum -y install terraform


  - name: create tf cloud config file with content
    copy:
      dest: "/var/lib/awx/.terraform.d/credentials.tfrc.json"
      content: |
        credentials "app.terraform.io" {
          token = "{{ lookup("env", "TF_TOKEN") }}"
        }

  - name: update safe directory
    command: git config --global --add safe.directory /opt/avail_repo
    check_mode: no

  # Clones the private repository in the private_clone folder inside the *opt* directory.
  - name: Clone private terraform repo
    ansible.builtin.git:
      repo: 'https://{{ lookup("env", "PAT_TOKEN") }}@github.com/maticnetwork/avail-deployment.git'
      dest: /opt/avail_repo
      clone: yes
      accept_hostkey: true
      version: dan/awx_integration
      force: yes
      update: yes
    ignore_errors: false
    no_log: false
    register: git_clone

  - name: init terraform run plan and apply
    shell:
      cmd: |
        cd /opt/avail_repo/tf/nets/devnet01
        terraform init
        terraform plan
    register: new_nodes

  # - debug:
  #     msg: "{{ ''.join(new_nodes.stdout_lines) | replace('\\e[0m', '') | replace('\\t', '') | replace('\\u001b', '') | replace('\u001b', '') }}"

  - debug:
      var: new_nodes.stdout | regex_replace('\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]', '')

#
#   - name: Add new instance to host group
#     add_host:
#       hostname: "{{ item }}"
#       groupname: launched
#     loop: "{{ new_nodes.stdout_lines[-1] }}"
#
# - name: Configure instance(s)
#   hosts: launched
#   become: yes
#   gather_facts: True
#   vars:
#     create_containers: 1
#     default_container_name: bor
#     default_container_image: 0xpolygon/bor:0.3.0-beta3
#   tasks:
#     - name: Wait for sudo
#       become: yes
#       shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
#     - name: Install aptitude
#       apt:
#         name: aptitude
#         state: latest
#         update_cache: true
#     - name: Install required system packages
#       apt:
#         pkg:
#           - apt-transport-https
#           - ca-certificates
#           - curl
#           - software-properties-common
#           - python3-pip
#           - virtualenv
#           - python3-setuptools
#           - awscli
#         state: latest
#         update_cache: true
#     - name: Add Docker GPG apt Key
#       apt_key:
#         url: https://download.docker.com/linux/ubuntu/gpg
#         state: present
#     - name: Add Docker Repository
#       apt_repository:
#         repo: deb https://download.docker.com/linux/ubuntu focal stable
#         state: present
#     - name: Update apt and install docker-ce
#       apt:
#         name: docker-ce
#         state: latest
#         update_cache: true
#     - name: Install Docker Module for Python
#       pip:
#         name: docker
#     - name: Login ECR
#       shell: "{{ item }}"
#       environment:
#         AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
#         AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
#         AWS_REGION: us-east-2
#       with_items:
#        - $(aws ecr get-login -a-no-include-email --region us-east-2)
#     - name: Pull default docker image
#       docker_image:
#         name: "{{ default_container_image }}"
#         source: pull
#     - name: Create and run container
#       docker_container:
#         name: "{{ default_container_name }}{{ item }}"
#         image: "{{ default_container_image }}"
#         state: started
#         ports: "8080:80"
#         detach: yes
#         command: server
#       with_sequence: count={{ create_containers }}
#
# - name: teardown instances
#   hosts: localhost
#   tasks:
#     - name: teardown resources once done with testing
#       shell:
#         cmd: |
#           sleep 2m
#           cd /opt/tf_repo/aws/test-applications/us-east-2/ci_deployment_cluster
#           terraform init
#           terraform destroy -var 'instance_count={{ instance_count }}' -auto-approve
