- name: Configure instance(s)
  hosts: all
  gather_facts: True
  vars:
    - ansible_ssh_common_args: -o StrictHostKeyChecking=no -o ProxyCommand="sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --region us-west-2 --parameters 'portNumber=%p'\""
    - ansible_user: ubuntu
    - ansible_become: true
    - ansible_ssh_private_key_file: '/Users/dmoore/Downloads/awxSshKey.pem'
  tasks:
    - name: Wait for sudo
      become: yes
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
