version: "3.3"
services:
  validator1:
    container_name: validator1
    image: avail_dev:develop1
    build:
      context: ../images/da
      dockerfile: Dockerfile-dev
      args:
        - BRANCH=nonexisting_branch
        - FEATURES=
        - RUNTIME_BRANCH=nonexisting_branch
    tmpfs: /tmp
    volumes:
      - val_1_state:/da/state
      - ../volume/testnet/exec/:/da/exec:ro
      - ../volume/testnet/genesis:/da/genesis:ro
      - ../volume/testnet/validator1/node.key:/da/node.key:ro
      - ../volume/testnet/validator1/suri.txt:/da/suri.txt:ro
      - ../volume/testnet/validator1/keystore:/da/keystore
    command:
      --alice
      --base-path /da/state
      --name MATIC_VALIDATOR_1
      --keystore-path /da/keystore
      --execution native-else-wasm
      --in-peers 10
      --out-peers 10
    networks:
      - beyondnat

  validator2:
    container_name: validator2
    image: avail_dev:develop1
    tmpfs: /tmp
    volumes:
      - val_2_state:/da/state
      - ../volume/testnet/exec/:/da/exec:ro
      - ../volume/testnet/genesis:/da/genesis:ro
      - ../volume/testnet/validator2/node.key:/da/node.key:ro
      - ../volume/testnet/validator2/suri.txt:/da/suri.txt:ro
      - ../volume/testnet/validator2/keystore:/da/keystore
    command:
      --bob
      --base-path /da/state
      --name MATIC_VALIDATOR_2
      --keystore-path /da/keystore
      --execution native-else-wasm
      --in-peers 10
      --out-peers 10
    networks:
      - beyondnat

  validator3:
    container_name: validator3
    image: avail_dev:develop1
    tmpfs: /tmp
    volumes:
      - val_3_state:/da/state
      - ../volume/testnet/exec/:/da/exec:ro
      - ../volume/testnet/genesis:/da/genesis:ro
      - ../volume/testnet/validator3/node.key:/da/node.key:ro
      - ../volume/testnet/validator3/suri.txt:/da/suri.txt:ro
      - ../volume/testnet/validator3/keystore:/da/keystore
    command:
      --validator
      --base-path /da/state
      --name MATIC_VALIDATOR_3
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --execution native-else-wasm
      --in-peers 10
      --out-peers 10
    networks:
      - beyondnat

  validator_alyssa:
    container_name: validator_alyssa
    image: avail_dev:develop1
    volumes:
      - alyssa_state:/da/state
      - ../volume/testnet/exec/:/da/exec:ro
      - ../volume/testnet/genesis:/da/genesis:ro
      - ../volume/testnet/validator_alyssa/node.key:/da/node.key:ro
      - ../volume/testnet/validator_alyssa/suri.txt:/da/suri.txt:ro
      - ../volume/testnet/validator_alyssa/keystore:/da/keystore
    command:
      --validator
      --base-path /da/state
      --name MATIC_VALIDATOR_ALYSSA
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --execution native-else-wasm
      --in-peers 10
      --out-peers 10
    networks:
      - beyondnat

  sentry_node:
    container_name: sentry_node
    image: avail_dev:develop1
    volumes:
      - sentry_node_state:/da/state
      - ../volume/testnet/exec/:/da/exec:ro
      - ../volume/testnet/genesis:/da/genesis:ro
      - ../volume/testnet/full_node/node.key:/da/node.key:ro
      - ../volume/testnet/full_node/suri.txt:/da/suri.txt:ro
      - ../volume/testnet/full_node/keystore:/da/keystore
    ports:
      - 30330:30330
      - 9944:9944
    command:
      --base-path /da/state
      --name MATIC_SENTRY_NODE
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --execution native-else-wasm
      --in-peers 10
      --out-peers 10
      --port 30330
      --rpc-cors all
      --rpc-port 9944
      --unsafe-rpc-external
      --rpc-methods unsafe
      --state-pruning archive
      --enable-kate-rpc
    networks:
      beyondnat:
        ipv4_address: 17.0.0.100

  lightclient:
    build:  
        context: ../images/client
        dockerfile: Dockerfile-dev
        args:
          - LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "sentry_node:9944",
      "--",
      "/app/avail-light/start.sh"
    ]
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=7000
      - BLOCK_MATRIX_PARTITION="None"
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - BOOTSTRAPS=["/ip4/17.0.0.101/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - BLOCK_PROCESSING_DELAY=120
      - APP_ID=1
      - P2P_SEED=210
      - RELAYS=["/ip4/17.0.0.102/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
      - OTEL_COLLECTOR="http://otc:4317"
      - MODE="client"
      - MODE_SWITCH=false
      - ORIGIN="internal"
    restart: always
    extra_hosts:
      - "sentry_node:17.0.0.100"
      - "bootstraplc:17.0.0.101"
      - "relaylc:17.0.0.102"
    networks:
      - beyondnat

  lightserver_1:
    build:  
        context: ../images/client
        dockerfile: Dockerfile-dev
        args:
          - LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    restart: always
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "sentry_node:9944",
      "--",
      "/app/avail-light/start.sh"
    ]
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=7000
      - BLOCK_MATRIX_PARTITION="None"
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=211
      - APP_ID=1
      - BOOTSTRAPS=["/ip4/17.0.0.101/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - BLOCK_PROCESSING_DELAY=0
      - RELAYS=["/ip4/17.0.0.102/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
      - OTEL_COLLECTOR="http://otc:4317"
      - MODE="server"
      - MODE_SWITCH=false
      - ORIGIN="internal"
    extra_hosts:
      - "sentry_node:17.0.0.100"
      - "bootstraplc:17.0.0.101"
      - "relaylc:17.0.0.102"
    networks:
      - beyondnat

  lightserver_2:
    build:  
        context: ../images/client
        dockerfile: Dockerfile-dev
        args:
          - LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    restart: always
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "sentry_node:9944",
      "--",
      "/app/avail-light/start.sh"
    ]
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=7000
      - BLOCK_MATRIX_PARTITION="None"
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=212
      - APP_ID=1
      - BOOTSTRAPS=["/ip4/17.0.0.101/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - BLOCK_PROCESSING_DELAY=0
      - RELAYS=["/ip4/17.0.0.102/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
      - OTEL_COLLECTOR="http://otc:4317"
      - MODE="server"
      - MODE_SWITCH=false
      - ORIGIN="internal"
    extra_hosts:
      - "sentry_node:17.0.0.100"
      - "bootstraplc:17.0.0.101"
      - "relaylc:17.0.0.102"
    networks:
      - beyondnat

  lightserver_3:
    build:  
        context: ../images/client
        dockerfile: Dockerfile-dev
        args:
          - LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    restart: always
    entrypoint: [
      "wait-for-it",
      "-t", "30",
      "sentry_node:9944",
      "--",
      "/app/avail-light/start.sh"
    ]
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=7000
      - BLOCK_MATRIX_PARTITION="None"
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=213
      - APP_ID=1
      - BOOTSTRAPS=["/ip4/17.0.0.101/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - BLOCK_PROCESSING_DELAY=0
      - RELAYS=["/ip4/17.0.0.102/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
      - OTEL_COLLECTOR="http://otc:4317"
      - MODE="server"
      - MODE_SWITCH=false
      - ORIGIN="internal"
    extra_hosts:
      - "sentry_node:17.0.0.100"
      - "bootstraplc:17.0.0.101"
      - "relaylc:17.0.0.102"
    networks:
      - beyondnat
  
  fatclient_1:
    build:  
      context: ../images/fat
      dockerfile: Dockerfile-dev
      args:
        - FAT_LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    entrypoint: ["/app/avail-light/start.sh"]
    environment:
      - BLOCK_MATRIX_PARTITION="1/3"
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=9000
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=21
      - BOOTSTRAPS=["/dns4/bootstraplc/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - RELAYS=["/dns4/relaylc/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
    networks:
      - beyondnat
  
  fatclient_2:
    build:  
      context: ../images/fat
      dockerfile: Dockerfile-dev
      args:
        - FAT_LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    entrypoint: ["/app/avail-light/start.sh"]
    environment:
      - BLOCK_MATRIX_PARTITION="2/3"
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=9000
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=22
      - BOOTSTRAPS=["/dns4/bootstraplc/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - RELAYS=["/dns4/relaylc/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
    networks:
      - beyondnat

  fatclient_3:
    build:  
      context: ../images/fat
      dockerfile: Dockerfile-dev
      args:
        - FAT_LC_BRANCH=nonexisting_branch
    depends_on:
      - sentry_node
      - bootstraplc
    entrypoint: ["/app/avail-light/start.sh"]
    environment:
      - BLOCK_MATRIX_PARTITION="3/3"
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=9000
      - FULL_NODE_WS=["ws://sentry_node:9944"]
      - LOG_LEVEL="INFO"
      - P2P_SEED=23
      - BOOTSTRAPS=["/dns4/bootstraplc/tcp/5369/p2p/12D3KooWSDaGuV1ewhyAEYsA6rk52hJyeN16hDE6bNgyRt62x7ie"]
      - RELAYS=["/dns4/relaylc/tcp/38001/p2p/12D3KooWR3USn8DUFkm9v23yeY8vvtwHSqpnr5VnPptKXoiDK3E7"]
    networks:
      - beyondnat

  load-test-tool:
    image: availj/presto:latest
    depends_on:
      - sentry_node
      - bootstraplc
    restart: always
    network_mode: host  

  bootstraplc:
    container_name: bootstraplc
    build:  
        context: ../images/bootstrap
        dockerfile: Dockerfile-dev
        args:
          - BOOTSTRAPLC_BRANCH=nonexisting_branch
    ports:
      - 5369:5369
      - 5370:5370
    networks:
      beyondnat:
        ipv4_address: 17.0.0.101

  relaylc:
    container_name: relaylc
    build:
        context: ../images/relay
        dockerfile: Dockerfile-dev
        args:
          - RELAY_BRANCH=nonexisting_branch
    ports:
      - 38000:38000
      - 38001:38001
    networks:
      beyondnat:
        ipv4_address: 17.0.0.102

  otc:
    image: otel/opentelemetry-collector-contrib:0.89.0
    volumes:
      - ./obs_config/otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: --config /etc/otelcol/config.yaml
    ports:
      - 1888:1888 
      - 8888:8888 
      - 8889:8889 
      - 13133:13133 
      - 4317:4317 
      - 4318:4318
      - 55679:55679 
    networks:
      - beyondnat
    depends_on:
      - jaeger
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./obs_config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - beyondnat

  jaeger:
    networks:
      - beyondnat
    image: jaegertracing/all-in-one:latest
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    ports:
      - "16686:16686"

volumes:
  val_1_state:
  val_2_state:
  val_3_state:
  sentry_node_state:
  alyssa_state:

networks:
  beyondnat:
    ipam:
      config:
        - subnet: 17.0.0.0/16
