- name: Create folder for templates
  ansible.builtin.file: 
    path: "{{ node_base_path }}"
    state: directory 
    mode: '0750'

- name: create kong proxy configuration
  ansible.builtin.template:
    src: "./templates/kong.yml"
    dest: "{{ node_base_path }}/kong.yml"
    mode: '0644'

- name: send kong proxy enviroment file
  ansible.builtin.copy:
    src: kong.env
    dest: "{{ node_base_path }}/kong.env"

- name: create internal kong network
  community.docker.docker_network:
    name: kong_internal_net 

- name: create kong general upstream network
  community.docker.docker_network:
    name: kong_upstream_net

- name: create kong db
  community.docker.docker_container:
    name: redis
    image:  redis:6-alpine
    command: "redis-server --save 60 1"
    volumes:
      - /data
    network_mode: kong_internal_net

- name: create kong proxy
  community.docker.docker_container:
    name: proxy 
    image: kong:2.6.0-alpine
    state: started
    restart: yes
    env_file: "{{ node_base_path }}/kong.env"
    volumes:
      - "{{ node_base_path }}/kong.yml:/proxy/kong.yml:ro"
    ports:
      - 443:8443
      - 80:8000
    networks:
      - name: kong_internal_net
        links:
          - redis:redis
      - name: kong_upstream_net
        aliases:
          - proxy

- name: create explorer dapp
  community.docker.docker_container:
    name: dapp 
    image: 0xpolygon/avail-apps:{{ dapp_docker_tag }}
    env:
      WS_URL: ws://{{ node.web_domain }}/ws
    network_mode: kong_upstream_net
