FROM docker.io/library/rust:1.78.0-bookworm AS base

FROM docker.io/library/debian:bookworm-slim AS runtime
RUN apt update && apt install -y libssl-dev libpq-dev ca-certificates

FROM base AS chef
RUN cargo install --locked cargo-chef
RUN apt update && apt install -y cmake git

FROM chef AS planner
WORKDIR /app
RUN git clone https://github.com/availproject/gas-relay-service.git .

RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS cacher
COPY --from=planner /app/recipe.json /app/recipe.json
WORKDIR /app
RUN cargo chef cook --recipe-path recipe.json

FROM base AS builder
WORKDIR /app
RUN git clone https://github.com/availproject/gas-relay-service.git .

COPY --from=cacher /target target
COPY --from=cacher /usr/local/cargo /usr/local/cargo

RUN cargo build

FROM runtime AS service
WORKDIR /app

COPY --from=service-builder /target/debug/ /
COPY --from=service-builder /public_key.pem /public_key.pem /
ENTRYPOINT ["/gas_relay_service"]
ENTRYPOINT ["/gas_relay_service"]
